version: '3'
services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_pg_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microORM
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - microORM

networks:
  microORM:


#docker-compose -f docker-compose.override.yml up --build
#docker-compose up --build
